name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies for Server
      run: dotnet restore TestProjectServer
    - name: Restore dependencies for Client
      run: dotnet restore TestProjectClient
    - name: Build Server
      run: dotnet build TestProjectServer --no-restore
    - name: Build Client
      run: dotnet build TestProjectClient --no-restore
    - name: Test
      run: dotnet test Test --verbosity normal



